plugins {
	id 'java'
	id 'net.fabricmc.fabric-loom-remap' version '1.17.20'
	id 'ploceus' version '1.17.7'
}

loom {
}

base {
	archivesName = project.archives_base_name
}
version = "${project.version}+mc${project.minecraft_version}"
group = project.maven_group

ploceus {
	setIntermediaryGeneration(2)
}

repositories {
	// Add repositories to retrieve artifacts from in here.
	// You should only use this when depending on other mods because
	// Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
	// See https://docs.gradle.org/current/userguide/declaring_repositories.html
	// for more information about repositories.
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	clientExceptions ploceus.raven(project.client_raven_build, 'client')
	serverExceptions ploceus.raven(project.server_raven_build, 'server')
	clientSignatures ploceus.sparrow(project.client_sparrow_build, 'client')
	serverSignatures ploceus.sparrow(project.server_sparrow_build, 'server')
	clientNests ploceus.nests(project.client_nests_build, 'client')
	serverNests ploceus.nests(project.server_nests_build, 'server')
	mappings ploceus.featherMappings(project.feather_build)

	ploceus.dependOsl(project.osl_version)
}

processResources {
	inputs.property 'version', version
	inputs.property 'minecraft_version', minecraft_version

	filesMatching('fabric.mod.json') {
		expand (
			'version': version,
			'minecraft_version': minecraft_version
		)
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = 'UTF-8'
	it.options.release = 8
}

java {
	// Still required by IDEs such as Eclipse and Visual Studio Code
	sourceCompatibility = JavaVersion.VERSION_1_8
	targetCompatibility = JavaVersion.VERSION_1_8

	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	// If this mod is going to be a library, then it should also generate Javadocs in order to aid with development.
	// Uncomment this line to generate them.
	// withJavadocJar()
}

// If you plan to use a different file for the license, don't forget to change the file name here!
jar {
	from('LICENSE') {
		rename { "${it}_${base.archivesName.get()}" }
	}
}
